### ISSUE TITLE
'bash.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by set** [faustinoaq/crystal-windows-installer#1]
I run crystal-setup.exe and finish installation. After, when i run "crystal" command, gave this error message. What's the problem ?

**Comment by faustinoaq** [comment]
Hi @set , currently this unofficial project just creates a shorcut for `bash.exe -c crystal`

> [**On README.md:**](https://github.com/faustinoaq/crystal-windows-installer#crystal-executable-on-windows-10) Currently this project is a bat file that execute crystal inside the **Linux Subsystem on Windows**.

In the future this project will install native crystal support for Windows. There is some [progress on crystal repo](https://github.com/crystal-lang/crystal/pull/3582) but still needs a lot of work to port it completely. Recently thanks to @RX14 we will be able to cross-compile a ["hello world" for windows](https://github.com/crystal-lang/crystal/pull/3582) 😄

**Comment by falfiya** [comment]
The problem is probably that you don't have WSL enabled, @set
