### ISSUE TITLE
missing VCRUNTIME140.dll

### ISSUE THREAD

**Issue by ghost** [faustinoaq/crystal-windows-installer#2]
Hi @faustinoaq 

after first (and clean) install of all this happens:

![image](https://user-images.githubusercontent.com/39699022/40802815-015aa408-6517-11e8-8697-e9cf0ea30b74.png)

So, it could be nice to put it to your requirements or push it while installing :-)

I installed Visual C++ Redistributable for Visual Studio 2015 and is ok.

However - great work! many!! thanks 👍

**Comment by faustinoaq** [comment]
> So, it could be nice to put it to your requirements or push it while installing :-)

@BenDietze Done! https://github.com/faustinoaq/crystal-windows-installer#prerequisites
